In [180]:
import numpy as np
#3-9, 13, 17, 19

def task_3():
    try:
        inputTXT = '''Вводится 4 числа n, m, r, c. Вивести масив розміру n на m, в якому в кожному r -му рядку і в кожному с-му стовбчику стоять 0, а інші елементи дорівнюють 1.\n'''
        n, m, r, c = [int(i) for i in input(inputTXT).split()]
        x = np.ones((n, m))
        x[::, ::c] = 0
        x[::r, ::] = 0
        print(x)
    except ValueError as VE:
        print('Не можливий формат введених значень, потрібно ввести чотири цілих числа')

def task_4():
    try:
        inputTXT = 'Вводится числа n, m. Вивести масив розміру n на m, в якому в якому у першому рядку (з нульовим індексом) йдуть числа від 0 до m-1, а всі інші елементи дорівнюють 0.\n'
        n, m = [int(i) for i in input(inputTXT).split()]
        x = np.arange(n*m)
        x = x.reshape(n, m)
        x[1::, ::] = 0
        print(x)
    except ValueError as VE:
        print('Не можливий формат введених значень, потрібно ввести два цілих числа')
        
def task_5():
    try:
        inputTXT = 'Вводится числа n. Вивести масив розміру n на n, в рядках з парними індексами стоять 1, а в інших - 0.\n'
        n = int(input(inputTXT))
        x = np.ones((n, n))
        x[1::2, ::] = 0
        print(x)
    except ValueError as VE:
        print('Не можливий формат введених значень, потрібно ввести ціле число')
        
def task_6():
    try:
        inputTXT = 'З клавіатури вводится масив. Змінити всі нульові елементи на -1.\n'
        n = [int(i) for i in input(inputTXT).split()]
        x = np.array(n)
        x[x != 0] = -1
        print(x)
    except ValueError as VE:
        print('Не можливий формат введених значень, потрібно ввести цілі числа')
    
def task_7():
    try:
        inputTXT = 'З клавіатури вводится масив. Замінити всі нульові елементи на -1.\n'
        n = [int(i) for i in input(inputTXT).split()]
        x = np.array(n)
        x[x == 0] = -1
        print(x)
    except ValueError as VE:
        print('Не можливий формат введених значень, потрібно ввести цілі числа')
        
def task_8():
    try:
        inputTXT = 'З клавіатури вводится масив. Підрахувати в ньому кількість нульових та ненульових елементів.\n'
        n = [int(i) for i in input(inputTXT).split()]
        x = np.array(n)
        print('Нулів: ', len(x[x == 0]))
        print('Не нулів: ', len(x[x != 0]))
    except ValueError as VE:
        print('Не можливий формат введених значень, потрібно ввести цілі числа')
        
def task_9():
    try:
        inputTXT = 'Вводится числа n. Створити масив значень від n до 0.\n'
        n = int(input(inputTXT))
        x = np.arange(n, -1, -1)
        print(x)
    except ValueError as VE:
        print('Не можливий формат введених значень, потрібно ввести ціле число')
        
def task_13():
    try:
        n = 4
        m = 5
        k = 6
        h = 100-1
        x = (h // (m*k), (h % (m*k))//k, (h % (m*k)) % k)
        #x[1::, ::] = 0
        print('В матриці {}х{}х{} індексом {} елементу є {}'.format(n, m, k, h+1, str(x)))
    except ValueError as VE:
        print('Не можливий формат введених значень')
        
def task_17():
    try:
        inputTXT = 'Вводится числа n. Заповнити вектор значеннями від 0 до n. Всі значення, що більше n/2 та менші за 3n/4 замінити нулями.\n'
        n = int(input(inputTXT))
        x = np.arange(n+1)
        l, r = np.split(x, [n//4+1])
        r[r < 3*n/4] = 0
        print(x)
    except ValueError as VE:
        print('Не можливий формат введених значень, потрібно ввести два цілих числа')
        
def task_19():
    try: 
        inputTXT = 'Вводится числа n. Згенерувати вектор із n випадкових чисел в діапазоні від 0 до 99. Визначити кількість унікальних чисел послідовності.\n'
        n = int(input(inputTXT))
        x = np.random.randint(0, 99, (n,))
        print('В послідовності {} - {} унікальних чисел.'.format(str(x), len(np.unique(x))))
    except ValueError as VE:
        print('Не можливий формат введених значень, потрібно ввести ціле число')

def task_manager():
    try: 
        tasks = {3: task_3, 
                 4: task_4, 
                 5: task_5, 
                 6: task_6, 
                 7: task_7, 
                 8: task_8,
                 9: task_9,
                 13: task_13,
                 17: task_17,
                 19: task_19}
        n = int(input('Оберіть завдання серед списку {}:\n'.format(list(tasks.keys()))))
        if n in tasks:
            tasks[n]()
        else:
            print('Схоже, нема такого завдання')
    except ValueError as VE:
        print('Не можливий формат введених значень, потрібно ввести ціле число')
        
def ex_2():
    a = np.array([[2, 1, -5, 1],
                [1, -3, 0, -6],
                [0, 2, -1, 2],
                [1, 4, -7, 6]])
    b = np.array([8, 9, -5, 0])
    detA = np.linalg.det(a)
    print('Детермінант основної матриці =', detA)
    x = a.copy()
    x[::,0] = b
    print('\n{}\nДетермінант = {}'.format(x, np.linalg.det(x)))
    x1 = np.linalg.det(x) / detA
    x = a.copy()
    x[::,1] = b
    print('\n{}\nДетермінант{}'.format(x, np.linalg.det(x)))
    x2 = np.linalg.det(x) / detA
    x = a.copy()
    x[::,2] = b
    print('\n{}\nДетермінант{}'.format(x, np.linalg.det(x)))
    x3 = np.linalg.det(x) / detA
    x = a.copy()
    x[::,3] = b
    print('\n{}\nДетермінант{}'.format(x, np.linalg.det(x)))
    x4 = np.linalg.det(x) / detA
    print('Власна реалізація методу Крамера:', x1, x2, x3, x4)
    print('Перевірка методом linalg.solve():', np.allclose(np.linalg.solve(a, b), [x1, x2, x3, x4]))
    
def ex_3():
    a = np.array([[5, 3, -1],
                  [2, -2, 0],
                  [3, -1, 2]])
    b = np.array([[1, 4, 16],
                  [-3, -2, 0],
                  [5, 7, 2]])
    print('2(A-0.5B) + AB:\n', 2*(a-0.5*b)+a*b)
    
def ex_4():
    a = np.array([[4, 2, 1],
                  [3, -2, 0],
                  [0, -1, 2]])
    b = np.array([[2, 0, 2],
                  [5, -7, -2],
                  [1, 0, -1]])
    x = np.linalg.inv(a)@b
    print('Множенням матриць A^(-1)*B отримали X:\n', x)
    print('Перевірка, A*X:\n', np.allclose(a@x, b))


#### Завдання 1. Виконати вправи 3, 4, 5, 6, 7, 8, 9, 13, 17, 19 ####
Для перевірки завдань запустіть у наступній комірці функцію:
###### task_manager() ######

In [165]:
task_manager()

Оберіть завдання серед списку [3, 4, 5, 6, 7, 8, 9, 13, 17, 19]:
3
Вводится 4 числа n, m, r, c. Вивести масив розміру n на m, в якому в кожному r -му рядку і в кожному с-му стовбчику стоять 0, а інші елементи дорівнюють 1.
7 8 4 3
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 1. 1. 0. 1.]
 [0. 1. 1. 0. 1. 1. 0. 1.]
 [0. 1. 1. 0. 1. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 1. 1. 0. 1.]
 [0. 1. 1. 0. 1. 1. 0. 1.]]


In [166]:
task_manager()

Оберіть завдання серед списку [3, 4, 5, 6, 7, 8, 9, 13, 17, 19]:
4
Вводится числа n, m. Вивести масив розміру n на m, в якому в якому у першому рядку (з нульовим індексом) йдуть числа від 0 до m-1, а всі інші елементи дорівнюють 0.
4 9
[[0 1 2 3 4 5 6 7 8]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


In [167]:
task_manager()

Оберіть завдання серед списку [3, 4, 5, 6, 7, 8, 9, 13, 17, 19]:
5
Вводится числа n. Вивести масив розміру n на n, в рядках з парними індексами стоять 1, а в інших - 0.
5
[[1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]]


In [168]:
task_manager()

Оберіть завдання серед списку [3, 4, 5, 6, 7, 8, 9, 13, 17, 19]:
6
З клавіатури вводится масив. Змінити всі нульові елементи на -1.
5 9 0 -3 5 0 3 0 0 4 -3 -4
[-1 -1  0 -1 -1  0 -1  0  0 -1 -1 -1]


In [170]:
task_manager()

Оберіть завдання серед списку [3, 4, 5, 6, 7, 8, 9, 13, 17, 19]:
7
З клавіатури вводится масив. Замінити всі нульові елементи на -1.
5 9 0 -3 5 0 3 0 0 4 -3 -4
[ 5  9 -1 -3  5 -1  3 -1 -1  4 -3 -4]


In [171]:
task_manager()

Оберіть завдання серед списку [3, 4, 5, 6, 7, 8, 9, 13, 17, 19]:
8
З клавіатури вводится масив. Підрахувати в ньому кількість нульових та ненульових елементів.
5 9 0 -3 5 0 3 0 0 4 -3 -4
Нулів:  4
Не нулів:  8


In [172]:
task_manager()

Оберіть завдання серед списку [3, 4, 5, 6, 7, 8, 9, 13, 17, 19]:
9
Вводится числа n. Створити масив значень від n до 0.
10
[10  9  8  7  6  5  4  3  2  1  0]


In [173]:
task_manager()

Оберіть завдання серед списку [3, 4, 5, 6, 7, 8, 9, 13, 17, 19]:
13
В матриці 4х5х6 індексом 100 елементу є (3, 1, 3)


In [174]:
task_manager()

Оберіть завдання серед списку [3, 4, 5, 6, 7, 8, 9, 13, 17, 19]:
17
Вводится числа n. Заповнити вектор значеннями від 0 до n. Всі значення, що більше n/2 та менші за 3n/4 замінити нулями.
10
[ 0  1  2  0  0  0  0  0  8  9 10]


In [175]:
task_manager()

Оберіть завдання серед списку [3, 4, 5, 6, 7, 8, 9, 13, 17, 19]:
19
Вводится числа n. Згенерувати вектор із n випадкових чисел в діапазоні від 0 до 99. Визначити кількість унікальних чисел послідовності.
30
В послідовності [60 73 38 25 85 41 36  0 60  5 89 18 65 72 86  6 54 63 53 74 73 76 69 49
 15 82 28 61 69 23] - 27 унікальних чисел.


#### Завдання 2. Розв'язати систему методом Крамера та порівняти з методом linalg.solve(): ####
$$
\left\{
    \begin{array}\\
        2x_1 + x_2 - 5x_3 + x_4 & \mbox{= } \ 8 \\
        x_1 - 3x_2 - 6x_4 & \mbox{= } \ 9 \\
        2x_2 - x_3 + 2x_4 & \mbox{= } \ -5 \\
        x_1 + 4x_2 - 7x_3 + 6x_4 & \mbox{=} \ 0
    \end{array}
\right.
$$

In [181]:
ex_2()

Детермінант основної матриці = 27.0

[[ 8  1 -5  1]
 [ 9 -3  0 -6]
 [-5  2 -1  2]
 [ 0  4 -7  6]]
Детермінант = 80.99999999999996

[[ 2  8 -5  1]
 [ 1  9  0 -6]
 [ 0 -5 -1  2]
 [ 1  0 -7  6]]
Детермінант-108.00000000000003

[[ 2  1  8  1]
 [ 1 -3  9 -6]
 [ 0  2 -5  2]
 [ 1  4  0  6]]
Детермінант-27.000000000000014

[[ 2  1 -5  8]
 [ 1 -3  0  9]
 [ 0  2 -1 -5]
 [ 1  4 -7  0]]
Детермінант27.000000000000014
Власна реалізація методу Крамера: 2.9999999999999982 -4.000000000000001 -1.0000000000000004 1.0000000000000004
Перевірка методом linalg.solve(): True


#### Завдання 3. Обчислити значення матричного виразу: ####

$$
2(A-0,5B)+AB, де A = 
\begin{pmatrix}\
    5 & 3 & -1 \\
    2 & -2 & 0 \\
    3 & -1 & 2 
\end{pmatrix}
 B =
\begin{pmatrix}\
    1 & 4 & 16 \\
    -3 & -2 & 0 \\
    5 & 7 & 2 
\end{pmatrix}
$$

In [137]:
ex_3()

2(A-0.5B) + AB:
 [[ 14.  14. -34.]
 [  1.   2.   0.]
 [ 16. -16.   6.]]


#### Завдання 4. Розв'язати рівняння за допомогою оберненої матриці й перевірити методом allclose() ####
$$
\begin{pmatrix}\
    5 & 3 & -1 \\
    2 & -2 & 0 \\
    3 & -1 & 2 
\end{pmatrix}
*X =
\begin{pmatrix}\
    1 & 4 & 16 \\
    -3 & -2 & 0 \\
    5 & 7 & 2 
\end{pmatrix}
$$

In [138]:
ex_4()

Множенням матриць A^(-1)*B отримали X:
 [[ 1.         -1.12903226  0.        ]
 [-1.          1.80645161  1.        ]
 [ 0.          0.90322581  0.        ]]
Перевірка, A*X:
 True
